name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev/*
      - master

env:
  NODE_VERSION: 18

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: 👀 Checkout Code
        uses: actions/checkout@v3

      - name: ☕️ Use Java 11
        uses: JavaToolInstaller@0
        with:
          versionSpec: 11
          jdkArchitectureOption: x64
          jdkSourceOption: PreInstalled

      - name: 🏗 Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 📦 Install Dependencies
        run: yarn install --frozen-lockfile

      - name: 🧪 Run Tests
        run: yarn build:android
